export const GET_USER_PROFILE_REQUEST = "GET_USER_PROFILE_REQUEST"
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS"
export const GET_USER_PROFILE_FAILURE = "GET_USER_PROFILE_FAILURE"

export const UPDATE_USER_PROFILE_REQUEST = "UPDATE_USER_PROFILE_REQUEST"
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS"
export const UPDATE_USER_PROFILE_FAILURE = "UPDATE_USER_PROFILE_FAILURE"

export const GET_AUTHORIZE_USER_REQUEST = "GET_AUTHORIZE_USER_REQUEST"
export const GET_AUTHORIZE_USER_SUCCESS = "GET_AUTHORIZE_USER_SUCCESS"
export const GET_AUTHORIZE_USER_FAILURE = "GET_AUTHORIZE_USER_FAILURE"

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST"
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE"

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST"
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS"
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE"

export const GET_USER_TWEETS_REQUEST = "GET_USER_TWEETS_REQUEST"
export const GET_USER_TWEETS_SUCCESS = "GET_USER_TWEETS_SUCCESS"
export const GET_USER_TWEETS_FAILURE = "GET_USER_TWEETS_FAILURE"

export const GET_HOME_TWEETS_REQUEST = "GET_HOME_TWEETS_REQUEST"
export const GET_HOME_TWEETS_SUCCESS = "GET_HOME_TWEETS_SUCCESS"
export const GET_HOME_TWEETS_FAILURE = "GET_HOME_TWEETS_FAILURE"

export const GET_NOTIFICATIONS_REQUEST = "GET_NOTIFICATIONS_REQUEST"
export const GET_NOTIFICATIONS_SUCCESS = "GET_NOTIFICATIONS_SUCCESS"
export const GET_NOTIFICATIONS_FAILURE = "GET_NOTIFICATIONS_FAILURE"
